default: &default
 adapter: mysql2
 encoding: utf8
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: root
 password: pass
 host: 127.0.0.1

development:
 <<: *default
 database: tensyoku_development
 port: 4306

test:
 <<: *default
 database: tensyoku_test

production:
 <<: *default
 database: tensyoku_production
